import type { Metadata } from "next";
import "@/styles/globals.css";
import { Inter as FontSans } from "next/font/google";

import MobileNavBar from "@/components/layout/mobile-nav-bar";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br" suppressHydrationWarning>
      <body className={fontSans.className}>
        <div className="flex flex-col">
          {children}
          <div className="h-20">
            <MobileNavBar />
          </div>
        </div>
      </body>
    </html>
  );
}
